// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (odoo_id, name, email, department, job_title, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, odoo_id, name, email, department, job_title, status, created_at, updated_at
`

type CreateEmployeeParams struct {
	OdooID     pgtype.Int4
	Name       string
	Email      string
	Department string
	JobTitle   string
	Status     string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OdooID,
		arg.Name,
		arg.Email,
		arg.Department,
		arg.JobTitle,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE id = $1
`

func (q *Queries) GetEmployee(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByOdooID = `-- name: GetEmployeeByOdooID :one
SELECT id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE odoo_id = $1
`

func (q *Queries) GetEmployeeByOdooID(ctx context.Context, odooID pgtype.Int4) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByOdooID, odooID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE status = coalesce($3, status)
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32
	Offset int32
	Status pgtype.Text
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OdooID,
			&i.Name,
			&i.Email,
			&i.Department,
			&i.JobTitle,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET name = $2, email = $3, department = $4, job_title = $5, status = $6, updated_at = now()
WHERE id = $1
RETURNING id, odoo_id, name, email, department, job_title, status, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID         pgtype.UUID
	Name       string
	Email      string
	Department string
	JobTitle   string
	Status     string
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Department,
		arg.JobTitle,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
