// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (organization_id, odoo_id, name, email, department, job_title, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, odoo_id, name, email, department, job_title, status, created_at, updated_at
`

type CreateEmployeeParams struct {
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
}

type CreateEmployeeRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OrganizationID,
		arg.OdooID,
		arg.Name,
		arg.Email,
		arg.Department,
		arg.JobTitle,
		arg.Status,
	)
	var i CreateEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, organization_id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE id = $1 AND organization_id = $2
`

type GetEmployeeParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

type GetEmployeeRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.ID, arg.OrganizationID)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByOdooID = `-- name: GetEmployeeByOdooID :one
SELECT id, organization_id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE odoo_id = $1 AND organization_id = $2
`

type GetEmployeeByOdooIDParams struct {
	OdooID         pgtype.Int4
	OrganizationID pgtype.UUID
}

type GetEmployeeByOdooIDRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetEmployeeByOdooID(ctx context.Context, arg GetEmployeeByOdooIDParams) (GetEmployeeByOdooIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByOdooID, arg.OdooID, arg.OrganizationID)
	var i GetEmployeeByOdooIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, organization_id, odoo_id, name, email, department, job_title, status, created_at, updated_at
FROM employees
WHERE organization_id = $3 AND status = coalesce($4, status)
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit          int32
	Offset         int32
	OrganizationID pgtype.UUID
	Status         pgtype.Text
}

type ListEmployeesRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Limit,
		arg.Offset,
		arg.OrganizationID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OdooID,
			&i.Name,
			&i.Email,
			&i.Department,
			&i.JobTitle,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET name = $2, email = $3, department = $4, job_title = $5, status = $6, updated_at = now()
WHERE id = $1 AND organization_id = $7
RETURNING id, organization_id, odoo_id, name, email, department, job_title, status, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	OrganizationID pgtype.UUID
}

type UpdateEmployeeRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OdooID         pgtype.Int4
	Name           string
	Email          string
	Department     string
	JobTitle       string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (UpdateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Department,
		arg.JobTitle,
		arg.Status,
		arg.OrganizationID,
	)
	var i UpdateEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OdooID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
