// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID         pgtype.UUID
	OdooID     pgtype.Int4
	Name       string
	Email      string
	Department string
	JobTitle   string
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
