// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationMember = `-- name: AddOrganizationMember :exec
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (organization_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddOrganizationMemberParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, odoo_company_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name          string
	Slug          string
	OdooCompanyID int64
	Status        string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.OdooCompanyID,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstActiveOrganization = `-- name: GetFirstActiveOrganization :one
SELECT id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
FROM organizations
WHERE status = 'active'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstActiveOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getFirstActiveOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT
    om.organization_id,
    om.user_id,
    om.role,
    o.name AS organization_name,
    o.slug,
    o.odoo_company_id,
    o.status,
    o.subscription_status
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id
WHERE om.user_id = $1 AND om.organization_id = $2
`

type GetMembershipParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

type GetMembershipRow struct {
	OrganizationID     pgtype.UUID
	UserID             pgtype.UUID
	Role               string
	OrganizationName   string
	Slug               string
	OdooCompanyID      int64
	Status             string
	SubscriptionStatus string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OrganizationID)
	var i GetMembershipRow
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.OrganizationName,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.SubscriptionStatus,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByOdooCompanyID = `-- name: GetOrganizationByOdooCompanyID :one
SELECT id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
FROM organizations
WHERE odoo_company_id = $1
`

func (q *Queries) GetOrganizationByOdooCompanyID(ctx context.Context, odooCompanyID int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByOdooCompanyID, odooCompanyID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
FROM organizations
WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByStripeCustomerID = `-- name: GetOrganizationByStripeCustomerID :one
SELECT id, name, slug, odoo_company_id, status, stripe_customer_id, subscription_status, created_at, updated_at
FROM organizations
WHERE stripe_customer_id = $1
`

func (q *Queries) GetOrganizationByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByStripeCustomerID, stripeCustomerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OdooCompanyID,
		&i.Status,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
    om.organization_id,
    om.user_id,
    om.role,
    o.name AS organization_name,
    o.slug,
    o.odoo_company_id,
    o.status,
    o.subscription_status,
    o.created_at AS organization_created_at
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id
WHERE om.user_id = $1
ORDER BY om.created_at ASC
`

type ListMembershipsByUserRow struct {
	OrganizationID        pgtype.UUID
	UserID                pgtype.UUID
	Role                  string
	OrganizationName      string
	Slug                  string
	OdooCompanyID         int64
	Status                string
	SubscriptionStatus    string
	OrganizationCreatedAt pgtype.Timestamptz
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserRow
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.OrganizationName,
			&i.Slug,
			&i.OdooCompanyID,
			&i.Status,
			&i.SubscriptionStatus,
			&i.OrganizationCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationStripe = `-- name: UpdateOrganizationStripe :exec
UPDATE organizations
SET stripe_customer_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateOrganizationStripeParams struct {
	ID               pgtype.UUID
	StripeCustomerID pgtype.Text
}

func (q *Queries) UpdateOrganizationStripe(ctx context.Context, arg UpdateOrganizationStripeParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationStripe, arg.ID, arg.StripeCustomerID)
	return err
}

const updateOrganizationSubscription = `-- name: UpdateOrganizationSubscription :exec
UPDATE organizations
SET subscription_status = $2, updated_at = now()
WHERE id = $1
`

type UpdateOrganizationSubscriptionParams struct {
	ID                 pgtype.UUID
	SubscriptionStatus string
}

func (q *Queries) UpdateOrganizationSubscription(ctx context.Context, arg UpdateOrganizationSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationSubscription, arg.ID, arg.SubscriptionStatus)
	return err
}
