// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payroll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayrollRuns = `-- name: CountPayrollRuns :one
SELECT count(*)::bigint
FROM payroll_runs
WHERE organization_id = $1 AND status = coalesce($2, status)
`

type CountPayrollRunsParams struct {
	OrganizationID pgtype.UUID
	Status         pgtype.Text
}

func (q *Queries) CountPayrollRuns(ctx context.Context, arg CountPayrollRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayrollRuns, arg.OrganizationID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPayrollRun = `-- name: CreatePayrollRun :one
INSERT INTO payroll_runs (period_start, period_end, status, created_by, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at, organization_id
`

type CreatePayrollRunParams struct {
	PeriodStart    pgtype.Date
	PeriodEnd      pgtype.Date
	Status         string
	CreatedBy      pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) CreatePayrollRun(ctx context.Context, arg CreatePayrollRunParams) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, createPayrollRun,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.CreatedBy,
		arg.OrganizationID,
	)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ErrorDetails,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const createPayslip = `-- name: CreatePayslip :one
INSERT INTO payslips (payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details, created_at
`

type CreatePayslipParams struct {
	PayrollRunID           pgtype.UUID
	EmployeeOdooID         int32
	GrossSalaryStotinki    int64
	EmployerSocialStotinki int64
	EmployeeSocialStotinki int64
	EmployerHealthStotinki int64
	EmployeeHealthStotinki int64
	IncomeTaxStotinki      int64
	NetSalaryStotinki      int64
	CalculationDetails     []byte
}

func (q *Queries) CreatePayslip(ctx context.Context, arg CreatePayslipParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, createPayslip,
		arg.PayrollRunID,
		arg.EmployeeOdooID,
		arg.GrossSalaryStotinki,
		arg.EmployerSocialStotinki,
		arg.EmployeeSocialStotinki,
		arg.EmployerHealthStotinki,
		arg.EmployeeHealthStotinki,
		arg.IncomeTaxStotinki,
		arg.NetSalaryStotinki,
		arg.CalculationDetails,
	)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.PayrollRunID,
		&i.EmployeeOdooID,
		&i.GrossSalaryStotinki,
		&i.EmployerSocialStotinki,
		&i.EmployeeSocialStotinki,
		&i.EmployerHealthStotinki,
		&i.EmployeeHealthStotinki,
		&i.IncomeTaxStotinki,
		&i.NetSalaryStotinki,
		&i.CalculationDetails,
		&i.CreatedAt,
	)
	return i, err
}

const getPayrollRun = `-- name: GetPayrollRun :one
SELECT id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at, organization_id
FROM payroll_runs
WHERE id = $1 AND organization_id = $2
`

type GetPayrollRunParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetPayrollRun(ctx context.Context, arg GetPayrollRunParams) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, getPayrollRun, arg.ID, arg.OrganizationID)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ErrorDetails,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getPayrollRunByID = `-- name: GetPayrollRunByID :one
SELECT id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at, organization_id
FROM payroll_runs
WHERE id = $1
`

func (q *Queries) GetPayrollRunByID(ctx context.Context, id pgtype.UUID) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, getPayrollRunByID, id)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ErrorDetails,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getPayslip = `-- name: GetPayslip :one
SELECT p.id, p.payroll_run_id, p.employee_odoo_id, p.gross_salary_stotinki, p.employer_social_stotinki, p.employee_social_stotinki, p.employer_health_stotinki, p.employee_health_stotinki, p.income_tax_stotinki, p.net_salary_stotinki, p.calculation_details, p.created_at
FROM payslips p
JOIN payroll_runs r ON r.id = p.payroll_run_id
WHERE p.id = $1 AND r.organization_id = $2
`

type GetPayslipParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetPayslip(ctx context.Context, arg GetPayslipParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, getPayslip, arg.ID, arg.OrganizationID)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.PayrollRunID,
		&i.EmployeeOdooID,
		&i.GrossSalaryStotinki,
		&i.EmployerSocialStotinki,
		&i.EmployeeSocialStotinki,
		&i.EmployerHealthStotinki,
		&i.EmployeeHealthStotinki,
		&i.IncomeTaxStotinki,
		&i.NetSalaryStotinki,
		&i.CalculationDetails,
		&i.CreatedAt,
	)
	return i, err
}

const listPayrollRuns = `-- name: ListPayrollRuns :many
SELECT id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at, organization_id
FROM payroll_runs
WHERE organization_id = $3 AND status = coalesce($4, status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPayrollRunsParams struct {
	Limit          int32
	Offset         int32
	OrganizationID pgtype.UUID
	Status         pgtype.Text
}

func (q *Queries) ListPayrollRuns(ctx context.Context, arg ListPayrollRunsParams) ([]PayrollRun, error) {
	rows, err := q.db.Query(ctx, listPayrollRuns,
		arg.Limit,
		arg.Offset,
		arg.OrganizationID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollRun
	for rows.Next() {
		var i PayrollRun
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ErrorDetails,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayslipsByRun = `-- name: ListPayslipsByRun :many
SELECT p.id, p.payroll_run_id, p.employee_odoo_id, p.gross_salary_stotinki, p.employer_social_stotinki, p.employee_social_stotinki, p.employer_health_stotinki, p.employee_health_stotinki, p.income_tax_stotinki, p.net_salary_stotinki, p.calculation_details, p.created_at
FROM payslips p
JOIN payroll_runs r ON r.id = p.payroll_run_id
WHERE p.payroll_run_id = $1 AND r.organization_id = $2
ORDER BY p.employee_odoo_id
`

type ListPayslipsByRunParams struct {
	PayrollRunID   pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) ListPayslipsByRun(ctx context.Context, arg ListPayslipsByRunParams) ([]Payslip, error) {
	rows, err := q.db.Query(ctx, listPayslipsByRun, arg.PayrollRunID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payslip
	for rows.Next() {
		var i Payslip
		if err := rows.Scan(
			&i.ID,
			&i.PayrollRunID,
			&i.EmployeeOdooID,
			&i.GrossSalaryStotinki,
			&i.EmployerSocialStotinki,
			&i.EmployeeSocialStotinki,
			&i.EmployerHealthStotinki,
			&i.EmployeeHealthStotinki,
			&i.IncomeTaxStotinki,
			&i.NetSalaryStotinki,
			&i.CalculationDetails,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPayrollRunCompleted = `-- name: SetPayrollRunCompleted :exec
UPDATE payroll_runs SET status = 'completed', completed_at = now(), updated_at = now() WHERE id = $1 AND organization_id = $2
`

type SetPayrollRunCompletedParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) SetPayrollRunCompleted(ctx context.Context, arg SetPayrollRunCompletedParams) error {
	_, err := q.db.Exec(ctx, setPayrollRunCompleted, arg.ID, arg.OrganizationID)
	return err
}

const setPayrollRunCompletedByRunID = `-- name: SetPayrollRunCompletedByRunID :exec
UPDATE payroll_runs SET status = 'completed', completed_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetPayrollRunCompletedByRunID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPayrollRunCompletedByRunID, id)
	return err
}

const setPayrollRunError = `-- name: SetPayrollRunError :exec
UPDATE payroll_runs SET status = 'failed', error_details = $2, updated_at = now() WHERE id = $1 AND organization_id = $3
`

type SetPayrollRunErrorParams struct {
	ID             pgtype.UUID
	ErrorDetails   []byte
	OrganizationID pgtype.UUID
}

func (q *Queries) SetPayrollRunError(ctx context.Context, arg SetPayrollRunErrorParams) error {
	_, err := q.db.Exec(ctx, setPayrollRunError, arg.ID, arg.ErrorDetails, arg.OrganizationID)
	return err
}

const setPayrollRunErrorByRunID = `-- name: SetPayrollRunErrorByRunID :exec
UPDATE payroll_runs SET status = 'failed', error_details = $2, updated_at = now() WHERE id = $1
`

type SetPayrollRunErrorByRunIDParams struct {
	ID           pgtype.UUID
	ErrorDetails []byte
}

func (q *Queries) SetPayrollRunErrorByRunID(ctx context.Context, arg SetPayrollRunErrorByRunIDParams) error {
	_, err := q.db.Exec(ctx, setPayrollRunErrorByRunID, arg.ID, arg.ErrorDetails)
	return err
}

const updatePayrollRunStatus = `-- name: UpdatePayrollRunStatus :exec
UPDATE payroll_runs SET status = $2, updated_at = now() WHERE id = $1 AND organization_id = $3
`

type UpdatePayrollRunStatusParams struct {
	ID             pgtype.UUID
	Status         string
	OrganizationID pgtype.UUID
}

func (q *Queries) UpdatePayrollRunStatus(ctx context.Context, arg UpdatePayrollRunStatusParams) error {
	_, err := q.db.Exec(ctx, updatePayrollRunStatus, arg.ID, arg.Status, arg.OrganizationID)
	return err
}
