// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payroll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayrollRun = `-- name: CreatePayrollRun :one
INSERT INTO payroll_runs (period_start, period_end, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at
`

type CreatePayrollRunParams struct {
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Status      string
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreatePayrollRun(ctx context.Context, arg CreatePayrollRunParams) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, createPayrollRun,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.CreatedBy,
	)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ErrorDetails,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayslip = `-- name: CreatePayslip :one
INSERT INTO payslips (payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details, created_at
`

type CreatePayslipParams struct {
	PayrollRunID           pgtype.UUID
	EmployeeOdooID         int32
	GrossSalaryStotinki    int64
	EmployerSocialStotinki int64
	EmployeeSocialStotinki int64
	EmployerHealthStotinki int64
	EmployeeHealthStotinki int64
	IncomeTaxStotinki      int64
	NetSalaryStotinki      int64
	CalculationDetails     []byte
}

func (q *Queries) CreatePayslip(ctx context.Context, arg CreatePayslipParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, createPayslip,
		arg.PayrollRunID,
		arg.EmployeeOdooID,
		arg.GrossSalaryStotinki,
		arg.EmployerSocialStotinki,
		arg.EmployeeSocialStotinki,
		arg.EmployerHealthStotinki,
		arg.EmployeeHealthStotinki,
		arg.IncomeTaxStotinki,
		arg.NetSalaryStotinki,
		arg.CalculationDetails,
	)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.PayrollRunID,
		&i.EmployeeOdooID,
		&i.GrossSalaryStotinki,
		&i.EmployerSocialStotinki,
		&i.EmployeeSocialStotinki,
		&i.EmployerHealthStotinki,
		&i.EmployeeHealthStotinki,
		&i.IncomeTaxStotinki,
		&i.NetSalaryStotinki,
		&i.CalculationDetails,
		&i.CreatedAt,
	)
	return i, err
}

const getPayrollRun = `-- name: GetPayrollRun :one
SELECT id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at
FROM payroll_runs
WHERE id = $1
`

func (q *Queries) GetPayrollRun(ctx context.Context, id pgtype.UUID) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, getPayrollRun, id)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ErrorDetails,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayslip = `-- name: GetPayslip :one
SELECT id, payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details, created_at
FROM payslips
WHERE id = $1
`

func (q *Queries) GetPayslip(ctx context.Context, id pgtype.UUID) (Payslip, error) {
	row := q.db.QueryRow(ctx, getPayslip, id)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.PayrollRunID,
		&i.EmployeeOdooID,
		&i.GrossSalaryStotinki,
		&i.EmployerSocialStotinki,
		&i.EmployeeSocialStotinki,
		&i.EmployerHealthStotinki,
		&i.EmployeeHealthStotinki,
		&i.IncomeTaxStotinki,
		&i.NetSalaryStotinki,
		&i.CalculationDetails,
		&i.CreatedAt,
	)
	return i, err
}

const listPayrollRuns = `-- name: ListPayrollRuns :many
SELECT id, period_start, period_end, status, created_by, approved_by, error_details, completed_at, created_at, updated_at
FROM payroll_runs
WHERE status = coalesce($3, status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPayrollRunsParams struct {
	Limit  int32
	Offset int32
	Status pgtype.Text
}

func (q *Queries) ListPayrollRuns(ctx context.Context, arg ListPayrollRunsParams) ([]PayrollRun, error) {
	rows, err := q.db.Query(ctx, listPayrollRuns, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollRun
	for rows.Next() {
		var i PayrollRun
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ErrorDetails,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayslipsByRun = `-- name: ListPayslipsByRun :many
SELECT id, payroll_run_id, employee_odoo_id, gross_salary_stotinki, employer_social_stotinki, employee_social_stotinki, employer_health_stotinki, employee_health_stotinki, income_tax_stotinki, net_salary_stotinki, calculation_details, created_at
FROM payslips
WHERE payroll_run_id = $1
ORDER BY employee_odoo_id
`

func (q *Queries) ListPayslipsByRun(ctx context.Context, payrollRunID pgtype.UUID) ([]Payslip, error) {
	rows, err := q.db.Query(ctx, listPayslipsByRun, payrollRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payslip
	for rows.Next() {
		var i Payslip
		if err := rows.Scan(
			&i.ID,
			&i.PayrollRunID,
			&i.EmployeeOdooID,
			&i.GrossSalaryStotinki,
			&i.EmployerSocialStotinki,
			&i.EmployeeSocialStotinki,
			&i.EmployerHealthStotinki,
			&i.EmployeeHealthStotinki,
			&i.IncomeTaxStotinki,
			&i.NetSalaryStotinki,
			&i.CalculationDetails,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPayrollRunCompleted = `-- name: SetPayrollRunCompleted :exec
UPDATE payroll_runs SET status = 'completed', completed_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetPayrollRunCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPayrollRunCompleted, id)
	return err
}

const setPayrollRunError = `-- name: SetPayrollRunError :exec
UPDATE payroll_runs SET status = 'failed', error_details = $2, updated_at = now() WHERE id = $1
`

type SetPayrollRunErrorParams struct {
	ID           pgtype.UUID
	ErrorDetails []byte
}

func (q *Queries) SetPayrollRunError(ctx context.Context, arg SetPayrollRunErrorParams) error {
	_, err := q.db.Exec(ctx, setPayrollRunError, arg.ID, arg.ErrorDetails)
	return err
}

const updatePayrollRunStatus = `-- name: UpdatePayrollRunStatus :exec
UPDATE payroll_runs SET status = $2, updated_at = now() WHERE id = $1
`

type UpdatePayrollRunStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdatePayrollRunStatus(ctx context.Context, arg UpdatePayrollRunStatusParams) error {
	_, err := q.db.Exec(ctx, updatePayrollRunStatus, arg.ID, arg.Status)
	return err
}
