// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event, payload)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, event, payload, status, attempts, last_response_code, last_error, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID pgtype.UUID
	Event     string
	Payload   []byte
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.WebhookID, arg.Event, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastResponseCode,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookRegistration = `-- name: CreateWebhookRegistration :one
INSERT INTO webhook_registrations (url, events, secret, created_by, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, url, events, secret, active, created_by, organization_id, created_at
`

type CreateWebhookRegistrationParams struct {
	Url            string
	Events         []string
	Secret         string
	CreatedBy      pgtype.UUID
	OrganizationID pgtype.UUID
}

type CreateWebhookRegistrationRow struct {
	ID             pgtype.UUID
	Url            string
	Events         []string
	Secret         string
	Active         bool
	CreatedBy      pgtype.UUID
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateWebhookRegistration(ctx context.Context, arg CreateWebhookRegistrationParams) (CreateWebhookRegistrationRow, error) {
	row := q.db.QueryRow(ctx, createWebhookRegistration,
		arg.Url,
		arg.Events,
		arg.Secret,
		arg.CreatedBy,
		arg.OrganizationID,
	)
	var i CreateWebhookRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.Active,
		&i.CreatedBy,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateWebhook = `-- name: DeactivateWebhook :exec
UPDATE webhook_registrations SET active = false WHERE id = $1 AND organization_id = $2
`

type DeactivateWebhookParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) DeactivateWebhook(ctx context.Context, arg DeactivateWebhookParams) error {
	_, err := q.db.Exec(ctx, deactivateWebhook, arg.ID, arg.OrganizationID)
	return err
}

const getWebhookRegistration = `-- name: GetWebhookRegistration :one
SELECT id, url, events, secret, active, created_by, organization_id, created_at
FROM webhook_registrations
WHERE id = $1 AND organization_id = $2
`

type GetWebhookRegistrationParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

type GetWebhookRegistrationRow struct {
	ID             pgtype.UUID
	Url            string
	Events         []string
	Secret         string
	Active         bool
	CreatedBy      pgtype.UUID
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetWebhookRegistration(ctx context.Context, arg GetWebhookRegistrationParams) (GetWebhookRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getWebhookRegistration, arg.ID, arg.OrganizationID)
	var i GetWebhookRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.Active,
		&i.CreatedBy,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveriesByWebhook = `-- name: ListDeliveriesByWebhook :many
SELECT id, webhook_id, event, payload, status, attempts, last_response_code, last_error, created_at
FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveriesByWebhookParams struct {
	WebhookID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListDeliveriesByWebhook(ctx context.Context, arg ListDeliveriesByWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByWebhook, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastResponseCode,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, webhook_id, event, payload, status, attempts, last_response_code, last_error, created_at
FROM webhook_deliveries
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastResponseCode,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookRegistrations = `-- name: ListWebhookRegistrations :many
SELECT id, url, events, secret, active, created_by, organization_id, created_at
FROM webhook_registrations
WHERE active = true AND organization_id = $1
ORDER BY created_at DESC
`

type ListWebhookRegistrationsRow struct {
	ID             pgtype.UUID
	Url            string
	Events         []string
	Secret         string
	Active         bool
	CreatedBy      pgtype.UUID
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListWebhookRegistrations(ctx context.Context, organizationID pgtype.UUID) ([]ListWebhookRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookRegistrations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookRegistrationsRow
	for rows.Next() {
		var i ListWebhookRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.Active,
			&i.CreatedBy,
			&i.OrganizationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDeliveryStatus = `-- name: UpdateWebhookDeliveryStatus :exec
UPDATE webhook_deliveries SET status = $2, attempts = $3, last_response_code = $4, last_error = $5 WHERE id = $1
`

type UpdateWebhookDeliveryStatusParams struct {
	ID               pgtype.UUID
	Status           string
	Attempts         int32
	LastResponseCode pgtype.Int4
	LastError        pgtype.Text
}

func (q *Queries) UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastResponseCode,
		arg.LastError,
	)
	return err
}
