[options]
addons_path = /mnt/extra-addons/server-tools,/mnt/extra-addons/payroll,/mnt/extra-addons/hr,/mnt/extra-addons/hr-holidays,/mnt/extra-addons/hr-attendance,/mnt/extra-addons/hr-expense,/mnt/extra-addons/timesheet,/mnt/extra-addons/reporting-engine,/mnt/extra-addons/account-financial-reporting,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$25000$changeme
db_host = hr-odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo
list_db = False
proxy_mode = True
without_demo = all
