export { ApiClient } from './client.js'
export type { ApiClientOptions } from './client.js'
export { ApiError } from './errors.js'
export type {
  PaginatedResponse,
  AuthResponse,
  OdooEmployeeType,
  EmployeeStatus,
  Employee,
  EmployeeCreateInput,
  EmployeeListParams,
  Department,
  DepartmentCreateInput,
  DepartmentListParams,
  LeaveStatus,
  LeaveRequest,
  LeaveRequestCreateInput,
  LeaveListParams,
  ContractStatus,
  Contract,
  ContractListParams,
  TimesheetStatus,
  Timesheet,
  TimesheetListParams,
  AttendanceStatus,
  Attendance,
  AttendanceListParams,
  PayrollRunStatus,
  PayrollRun,
  PayrollRunListParams,
  PayslipStatus,
  Payslip,
  PayslipListParams,
  ExpenseStatus,
  Expense,
  ExpenseListParams,
  AppraisalStatus,
  Appraisal,
  AppraisalListParams,
  CourseStatus,
  Course,
  CourseListParams,
  UserStatus,
  User,
  UserListParams,
  OrgSettings,
  AuditLogEntry,
  AuditLogListParams,
  DashboardStats,
} from './types.js'
